package tui

// KeyPresets returns named preset binding sets in "context.action" -> keys form.
// Each preset is a complete binding set; "default" is empty (uses defaults).
func KeyPresets() map[string]map[string][]string {
	return map[string]map[string][]string{
		"default": {},
		"vim": {
			"problems.page_down": {"ctrl+d"},
			"problems.page_up":   {"ctrl+u"},
			"contests.page_down": {"ctrl+d"},
			"contests.page_up":   {"ctrl+u"},
			"stats.page_down":    {"ctrl+d", "ctrl+f"},
			"stats.page_up":      {"ctrl+u", "ctrl+b"},
			"problem.page_down":  {"ctrl+d", "ctrl+f"},
			"problem.page_up":    {"ctrl+u", "ctrl+b"},
			"help.page_next":     {"ctrl+f"},
			"help.page_prev":     {"ctrl+b"},
		},
		"arrows": {
			"problems.up":       {"up"},
			"problems.down":     {"down"},
			"contests.up":       {"up"},
			"contests.down":     {"down"},
			"contest.up":        {"up"},
			"contest.down":      {"down"},
			"stats.up":          {"up"},
			"stats.down":        {"down"},
			"stats.page_up":     {"pgup"},
			"stats.page_down":   {"pgdown"},
			"settings.up":       {"up"},
			"settings.down":     {"down"},
			"settings.top":      {"home"},
			"settings.bottom":   {"end"},
			"problem.up":        {"up"},
			"problem.down":      {"down"},
			"problem.page_up":   {"pgup"},
			"problem.page_down": {"pgdown"},
			"problem.top":       {"home"},
			"problem.bottom":    {"end"},
			"testmgr.up":        {"up"},
			"testmgr.down":      {"down"},
			"help.scroll_up":    {"up"},
			"help.scroll_down":  {"down"},
			"help.page_prev":    {"left"},
			"help.page_next":    {"right"},
		},
		"emacs": {
			"problems.down":      {"down", "ctrl+n"},
			"problems.up":        {"up", "ctrl+p"},
			"problems.page_down": {"pgdown", "ctrl+v"},
			"problems.page_up":   {"pgup", "alt+v"},
			"contests.down":      {"down", "ctrl+n"},
			"contests.up":        {"up", "ctrl+p"},
			"contests.page_down": {"pgdown", "ctrl+v"},
			"contests.page_up":   {"pgup", "alt+v"},
			"contest.down":       {"down", "ctrl+n"},
			"contest.up":         {"up", "ctrl+p"},
			"stats.down":         {"down", "ctrl+n"},
			"stats.up":           {"up", "ctrl+p"},
			"stats.page_down":    {"pgdown", "ctrl+v"},
			"stats.page_up":      {"pgup", "alt+v"},
			"settings.down":      {"down", "ctrl+n"},
			"settings.up":        {"up", "ctrl+p"},
			"problem.down":       {"down", "ctrl+n"},
			"problem.up":         {"up", "ctrl+p"},
			"problem.page_down":  {"pgdown", "ctrl+v"},
			"problem.page_up":    {"pgup", "alt+v"},
			"testmgr.down":       {"down", "ctrl+n"},
			"testmgr.up":         {"up", "ctrl+p"},
			"help.scroll_down":   {"down", "ctrl+n"},
			"help.scroll_up":     {"up", "ctrl+p"},
		},
	}
}
