#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Secrets live only in this process's memory for one run: never persisted, never printed.
ENV_FILE=/dev/null
cd "$(dirname "$0")"
OUT=out
mkdir -p "$OUT"
FIXTURE=../../internal/submit/testdata/submit-page.html

TOTAL_STAGES=5

banner "Issue #40 spike: direct submit against live Codeforces"

stage "Log in to Codeforces in Chrome"
say "The spike reuses your real browser session, so Cloudflare sees a normal user."
open_url "https://codeforces.com/enter"
step "Log in. Use Chrome (or Chromium/Brave): the spike imitates Chrome's TLS fingerprint."
step "Open https://codeforces.com/problemset/submit and check the page loads normally."
pause "Logged in and the submit page is visible? Press Enter."

stage "Copy the Cookie header"
say "Your browser sends this with every request. It is as sensitive as your password:"
say "it is read hidden, kept in memory for this run only, and never written to disk."
step "On the submit page press F12 → Network tab → press F5 to reload."
step "Click the first request, named 'submit' (type: document)."
step "Headers tab → Request Headers → find 'cookie:' → right-click the value → Copy value."
note "Tip: if the paste is cut off at ~4000 characters, delete cookies you don't need and retry."
ask_secret CF_COOKIE "Paste the cookie header (hidden):"
[[ -n "$CF_COOKIE" ]] || { warn "empty cookie, aborting"; exit 1; }

stage "Copy the User-Agent"
say "It must match the browser that produced the cookie (Cloudflare checks the pair)."
step "Same Request Headers list → find 'user-agent:' → copy the value."
ask CF_UA "Paste the user-agent:"
[[ -n "$CF_UA" ]] || { warn "empty user-agent, aborting"; exit 1; }
ask CF_HANDLE "Your Codeforces handle:"
export CF_COOKIE CF_UA

stage "Step A: GET only (safe, posts nothing)"
say "Fetches the submit page, parses the form and compiler list, saves a scrubbed fixture."
say "csrf_token / ftaa / bfaa values are replaced with REDACTED before saving."
mkdir -p "$(dirname "$FIXTURE")"
go run . -fixture "$FIXTURE" 2>&1 | tee "$OUT/get.txt" || true
note "saved to $OUT/get.txt (gitignored)"
if ! grep -q "GET OK, form parsed" "$OUT/get.txt"; then
  warn "GET step did not reach 'form parsed'. See OUTCOME above."
  warn "That is itself the result: blocked / not logged in / layout changed. Post it on #40."
  pause "Press Enter to continue to the summary."
  SKIP_POST=1
else
  SKIP_POST=0
fi

stage "Step B: real POST (submits a Solution)"
if [[ "$SKIP_POST" == 1 ]]; then
  say "Skipped: step A did not succeed."
else
  say "This posts a REAL Submission to your account. Default: problem 4A (Watermelon),"
  say "a correct Python 3 solution, so the Verdict should be OK. It appears in your history."
  if confirm "Post the test Submission now?"; then
    SRC="$OUT/4A.py"
    printf 'w = int(input())\nprint("YES" if w > 2 and w %% 2 == 0 else "NO")\n' > "$SRC"
    go run . -post -contest 4 -problem A -lang "Python 3" -src "$SRC" -handle "$CF_HANDLE" 2>&1 | tee "$OUT/post.txt" || true
    note "saved to $OUT/post.txt (gitignored)"
    note "If you see 'exactly the same code', change the source slightly and re-run: that still proves the POST path."
  else
    say "Skipped by choice."
  fi
fi
unset CF_COOKIE CF_UA

stage "Record the outcome"
say "Nothing below contains your cookie. Review it, then post it on issue #40:"
printf '\n'
grep -h "OUTCOME\|^GET \|^POST \|compiler options\|hidden/input\|submission " "$OUT"/get.txt "$OUT"/post.txt 2>/dev/null | sed 's/^/    /' || true
printf '\n'
say "Post it:  gh issue comment 40 --body-file $OUT/comment.md"
{
  echo "Spike result (direct submit, tls-client Chrome_144):"
  echo '```'
  grep -h "OUTCOME\|^GET \|^POST \|compiler options\|submission " "$OUT"/get.txt "$OUT"/post.txt 2>/dev/null || true
  echo '```'
} > "$OUT/comment.md"
note "draft written to $OUT/comment.md; fixture at $FIXTURE (review with git diff before committing)"
pause "Done? Press Enter."

finish
